In [35]:
import seaborn as sns
df=sns.load_dataset('tips')

In [36]:
x=df[['day','size','sex','time','smoker']]
y=df['total_bill']

In [37]:
x

day  size     sex    time smoker
0     Sun     2  Female  Dinner     No
1     Sun     3    Male  Dinner     No
2     Sun     3    Male  Dinner     No
3     Sun     2    Male  Dinner     No
4     Sun     4  Female  Dinner     No
..    ...   ...     ...     ...    ...
239   Sat     3    Male  Dinner     No
240   Sat     2  Female  Dinner    Yes
241   Sat     2    Male  Dinner    Yes
242   Sat     2    Male  Dinner     No
243  Thur     2  Female  Dinner     No

[244 rows x 5 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder

le2=LabelEncoder()
le3=LabelEncoder()

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,train_size=.2,random_state=10)

In [40]:

X_train['smoker']=le2.fit_transform(X_train['smoker'])
X_train['time']=le3.fit_transform(X_train['time'])

In [41]:

X_test['smoker']=le2.transform(X_test['smoker'])
X_test['time']=le3.transform(X_test['time'])

In [42]:
X_train

day  size     sex  time  smoker
57    Sat     2  Female     0       0
31    Sat     4    Male     0       0
65    Sat     3    Male     0       0
140  Thur     2  Female     1       0
89   Thur     2    Male     1       0
158   Sun     2  Female     0       0
30    Sat     2    Male     0       0
86   Thur     2    Male     1       0
92    Fri     2  Female     0       1
141  Thur     6    Male     1       0
126  Thur     2    Male     1       0
153   Sun     4    Male     0       0
13    Sun     4    Male     0       0
197  Thur     4  Female     1       1
77   Thur     4    Male     1       0
222   Fri     1    Male     1       1
179   Sun     2    Male     0       1
177   Sun     2    Male     0       1
206   Sat     3    Male     0       1
224   Fri     2    Male     1       1
200  Thur     3    Male     1       1
33    Sat     4  Female     0       0
62    Sat     2    Male     0       1
122  Thur     2    Male     1       0
107   Sat     2    Male     0       1
88   Thur     2    Male     1       0
54    Sun     4    Male     0       0
139  Thur     2  Female     1       0
100   Fri     2  Female     0       1
16    Sun     3  Female     0       0
115   Sun     2  Female     0       0
164   Sun     2  Female     0       1
40    Sat     3    Male     0       0
0     Sun     2  Female     0       0
73    Sat     2  Female     0       1
8     Sun     2    Male     0       0
238   Sat     3  Female     0       0
157   Sun     4  Female     0       0
221   Fri     2  Female     1       1
217   Sat     2    Male     0       1
156   Sun     6    Male     0       0
123  Thur     2    Male     1       0
113   Sun     2    Male     0       0
64    Sat     3    Male     0       0
15    Sun     2    Male     0       0
228   Sat     2    Male     0       0
125  Thur     6  Female     1       0
9     Sun     2    Male     0       0

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('Onehot',OneHotEncoder(drop='first'),[0])],remainder='passthrough')

In [44]:
X_train=ct.fit_transform(X_train)
X_train

array([[1.0, 0.0, 0.0, 2, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 4, 'Male', 0, 0],
       [1.0, 0.0, 0.0, 3, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 2, 'Female', 1, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 1.0, 0.0, 2, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 2, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 0.0, 0.0, 2, 'Female', 0, 1],
       [0.0, 0.0, 1.0, 6, 'Male', 1, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 1.0, 0.0, 4, 'Male', 0, 0],
       [0.0, 1.0, 0.0, 4, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 4, 'Female', 1, 1],
       [0.0, 0.0, 1.0, 4, 'Male', 1, 0],
       [0.0, 0.0, 0.0, 1, 'Male', 1, 1],
       [0.0, 1.0, 0.0, 2, 'Male', 0, 1],
       [0.0, 1.0, 0.0, 2, 'Male', 0, 1],
       [1.0, 0.0, 0.0, 3, 'Male', 0, 1],
       [0.0, 0.0, 0.0, 2, 'Male', 1, 1],
       [0.0, 0.0, 1.0, 3, 'Male', 1, 1],
       [1.0, 0.0, 0.0, 4, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 2, 'Male', 0, 1],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
    

In [45]:
X_test=ct.transform(X_test)

In [46]:
X_test

array([[0.0, 1.0, 0.0, ..., 'Female', 0, 0],
       [1.0, 0.0, 0.0, ..., 'Male', 0, 1],
       [1.0, 0.0, 0.0, ..., 'Male', 0, 1],
       ...,
       [0.0, 1.0, 0.0, ..., 'Female', 0, 0],
       [1.0, 0.0, 0.0, ..., 'Male', 0, 0],
       [1.0, 0.0, 0.0, ..., 'Male', 0, 0]], dtype=object)

In [50]:
X_train

array([[1.0, 0.0, 0.0, 2, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 4, 'Male', 0, 0],
       [1.0, 0.0, 0.0, 3, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 2, 'Female', 1, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 1.0, 0.0, 2, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 2, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 0.0, 0.0, 2, 'Female', 0, 1],
       [0.0, 0.0, 1.0, 6, 'Male', 1, 0],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
       [0.0, 1.0, 0.0, 4, 'Male', 0, 0],
       [0.0, 1.0, 0.0, 4, 'Male', 0, 0],
       [0.0, 0.0, 1.0, 4, 'Female', 1, 1],
       [0.0, 0.0, 1.0, 4, 'Male', 1, 0],
       [0.0, 0.0, 0.0, 1, 'Male', 1, 1],
       [0.0, 1.0, 0.0, 2, 'Male', 0, 1],
       [0.0, 1.0, 0.0, 2, 'Male', 0, 1],
       [1.0, 0.0, 0.0, 3, 'Male', 0, 1],
       [0.0, 0.0, 0.0, 2, 'Male', 1, 1],
       [0.0, 0.0, 1.0, 3, 'Male', 1, 1],
       [1.0, 0.0, 0.0, 4, 'Female', 0, 0],
       [1.0, 0.0, 0.0, 2, 'Male', 0, 1],
       [0.0, 0.0, 1.0, 2, 'Male', 1, 0],
    

In [65]:
X_train.shape

(48, 7)

In [77]:
x11=X_train[:,0:3]
y2=X_train[:,4]
x22=X_train[:,5:]

In [67]:
x11

array([[1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0],
       [0.0, 1.0, 0.0],
       [0.0, 0.0

In [71]:
x22

array([[0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0]], dtype=object)

In [78]:
y2


array(['Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male',
       'Male', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Male', 'Female', 'Male'], dtype=object)

In [73]:
import numpy as np
x2=np.hstack((x11,x22))
x2

array([[1.0, 0.0, 0.0, 0, 0],
       [1.0, 0.0, 0.0, 0, 0],
       [1.0, 0.0, 0.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 1.0, 0.0, 0, 0],
       [1.0, 0.0, 0.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 0.0, 0.0, 0, 1],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 1.0, 0.0, 0, 0],
       [0.0, 1.0, 0.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 1],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 0.0, 0.0, 1, 1],
       [0.0, 1.0, 0.0, 0, 1],
       [0.0, 1.0, 0.0, 0, 1],
       [1.0, 0.0, 0.0, 0, 1],
       [0.0, 0.0, 0.0, 1, 1],
       [0.0, 0.0, 1.0, 1, 1],
       [1.0, 0.0, 0.0, 0, 0],
       [1.0, 0.0, 0.0, 0, 1],
       [0.0, 0.0, 1.0, 1, 0],
       [1.0, 0.0, 0.0, 0, 1],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 1.0, 0.0, 0, 0],
       [0.0, 0.0, 1.0, 1, 0],
       [0.0, 0.0, 0.0, 0, 1],
       [0.0, 1.0, 0.0, 0, 0],
       [0.0, 1.0, 0.0, 0, 0],
       [0.0, 1.0, 0.0, 0, 1],
       [1.0, 0.0, 0.0, 0, 0],
       [0.

In [75]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()

In [79]:
from sklearn.model_selection import train_test_split
X2_train,X2_test,Y2_train,Y2_test=train_test_split(x2,y2,train_size=.2,random_state=10)

In [82]:
gnb.fit(X2_train,Y2_train)

GaussianNB()

In [85]:
y2_pred=gnb.predict(X2_test)

In [86]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(confusion_matrix(y2_pred,Y2_test))
print(accuracy_score(y2_pred,Y2_test))
print(classification_report(y2_pred,Y2_test))

[[ 7 20]
 [ 5  7]]
0.358974358974359
              precision    recall  f1-score   support

      Female       0.58      0.26      0.36        27
        Male       0.26      0.58      0.36        12

    accuracy                           0.36        39
   macro avg       0.42      0.42      0.36        39
weighted avg       0.48      0.36      0.36        39

