In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.datasets import make_classification
x,y=make_classification(n_classes=2,random_state=42,n_samples=1000,n_features=10)

In [5]:
pd.DataFrame(x,y)

0         1         2         3         4         5         6  \
0   0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1  -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
1  -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
0   1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
1  -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..       ...       ...       ...       ...       ...       ...       ...   
1  -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
1  -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
0   1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
0  -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
0   0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

           7         8         9  
0  -1.210161 -0.628077  1.227274  
1  -0.984534  0.363896  0.209470  
1  -0.246383 -1.058145 -0.297376  
0  -0.357445 -1.473127 -0.190039  
1  -0.939156  0.175915  0.236224  
..       ...       ...       ...  
1   1.428760  1.687092  1.072542  
1  -1.680870  1.798510  0.034272  
0   0.692723 -1.503850  0.225264  
0  -0.497354  2.472138  0.867187  
0   0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [5]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=42)

In [7]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [8]:
x_train.shape
y_train.shape

(700,)

In [9]:
lg.fit(x_train,y_train,)

LogisticRegression()

In [10]:
y_predict=lg.predict(x_test)
y_predict

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 

In [17]:
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [12]:
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import StratifiedKFold
cvs=StratifiedKFold()

In [13]:
# hyper paameter tuning (using gridsearchCV)
penalty=['l1','l2','elasticnet']
c_values=[.01,100,10,1,.1]
solver=['newton-cg','lbfgs','liblinear','sag','saga']

params=dict(penalty=penalty,C=c_values,solver=solver)

gs=GridSearchCV(estimator=lg,param_grid=params,scoring='accuracy',n_jobs=-1,cv=cvs)
gs
result=gs.fit(x_train,y_train)


/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  

In [14]:
print(result.best_score_)
print(result.best_params_)

0.8785714285714287
{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}


In [15]:
y_predict_new=gs.predict(x_test)

In [16]:
print(accuracy_score(y_test,y_predict_new))
print(confusion_matrix(y_test,y_predict_new))
print(classification_report(y_test,y_predict_new))

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



In [17]:
#LOGISTIC REGRESSION(MULTICLASS CLASSIFICATION )


In [18]:
from sklearn.datasets import make_classification
x1,y1=make_classification(n_classes=3,random_state=42,n_samples=1000,n_informative=3,n_features=10)

In [19]:
pd.DataFrame(x1,y1)

0         1         2         3         4         5         6  \
1   0.771533 -1.474336  2.196646 -0.678992  0.767479 -1.226179 -0.237566   
2   1.858383 -3.680880  0.227496 -3.818368  0.635968  1.609521 -0.153135   
1  -0.987248  1.539168  0.585904  1.185281 -0.736770 -1.406815  0.684783   
1  -1.022420  1.381787  2.015275  0.861434  1.290644 -1.889649  1.009138   
2  -0.131161 -2.079008  1.483744  1.636858 -0.734811 -0.640154  2.666422   
..       ...       ...       ...       ...       ...       ...       ...   
2   0.982677 -1.908917 -0.385673 -2.565989  0.434503 -1.334611 -0.060318   
1  -1.144949  1.434090 -0.459657  0.358606 -1.079842  0.918915  1.339638   
1  -1.227082  1.656028  0.472630  1.718125 -1.366858  0.018017  1.131626   
1   1.285276 -0.297152 -0.671721 -1.843337 -1.254161 -0.276889 -2.913304   
1  -0.754280  0.885161 -1.672894  0.652953  0.404213 -0.249072  0.904253   

           7         8         9  
1   0.681743  1.089962  0.962503  
2  -0.474178  1.341139 -0.771772  
1  -0.322028 -1.451034  1.325432  
1   0.363116 -1.844238  0.311110  
2  -1.085748 -0.892851  0.029796  
..       ...       ...       ...  
2   1.040062  0.433730 -0.739771  
1   1.193113 -2.473007  1.021515  
1  -0.863494 -1.839323 -0.031203  
1  -1.315441  2.854465  1.309444  
1  -2.036221 -1.439896  0.047493  

[1000 rows x 10 columns]

In [20]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=.3,random_state=42)

In [21]:
from sklearn.linear_model import LogisticRegression
lg1=LogisticRegression(multi_class='ovr')
lg1.fit(x1_train,y1_train)
y1_predict=lg1.predict(x1_test)

/Users/cybesama/Desktop/ML(nayak)/venv/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 
print(accuracy_score(y1_test,y1_predict))
print(confusion_matrix(y1_test,y1_predict))
print(classification_report(y1_test,y1_predict))

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



In [23]:
y1_predict

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 0,
       1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1,
       0, 1, 0, 1, 0, 2, 2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 2,
       1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0,
       2, 2, 2, 0, 0, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 2,
       1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2,
       0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2,
       0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 1])